// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! The menu-bar / system-tray item.
//!
//! Left click toggles the popover; right click opens a short menu. The menu
//! carries Quit because an agent application has no Dock icon and no
//! application menu — without it there would be no way to exit antiburn. It
//! also carries the popover's pin, which needs a surface that survives the
//! popover being dismissed — and the menu bar is the only one there is.
//!
//! Linux is different. The AppIndicator backend reports no click events, and
//! every click opens the menu. So the menu's first item, Open antiburn, is what
//! opens the popover there.

use tauri::AppHandle;
use tauri::image::Image;
use tauri::menu::{IsMenuItem, Menu, MenuEvent, MenuItem, PredefinedMenuItem};
use tauri::tray::{MouseButton, MouseButtonState, TrayIcon, TrayIconBuilder, TrayIconEvent};
use tauri::{Manager, Wry};

#[cfg(debug_assertions)]
use crate::commands;
use crate::{popover, settings};

/// The tray item's id, and how anything else gets a handle back to it.
pub const TRAY_ID: &str = "antiburn";

/// Generated by `apps/desktop/scripts/generate-icons.mjs`; see the icons
/// README for provenance. Embedded rather than read at runtime so a damaged
/// installation cannot leave the app running with no menu-bar presence.
const TRAY_ICON: &[u8] = include_bytes!("../icons/tray.png");

/// Linux only: the item that stands in for the click the backend never reports.
#[cfg(target_os = "linux")]
const MENU_OPEN: &str = "open";
const MENU_PIN: &str = "pin";
const MENU_SETTINGS: &str = "settings";
#[cfg(debug_assertions)]
const MENU_RESET_ONBOARDING: &str = "reset-onboarding";
const MENU_QUIT: &str = "quit";

/// Title case, matching "Quit antiburn" and the platform's own menus.
const PIN_LABEL: &str = "Pin Window";
const UNPIN_LABEL: &str = "Unpin Window";

/// Linux only, and title case for the same reason the pin labels are.
#[cfg(target_os = "linux")]
const OPEN_LABEL: &str = "Open antiburn";
#[cfg(debug_assertions)]
const RESET_ONBOARDING_LABEL: &str = "Reset Onboarding";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum TrayMenuEntry {
    #[cfg(target_os = "linux")]
    Open,
    Pin,
    Settings,
    #[cfg(debug_assertions)]
    ResetOnboarding,
    Separator,
    Quit,
}

#[cfg(all(target_os = "linux", debug_assertions))]
const MENU_LAYOUT: &[TrayMenuEntry] = &[
    TrayMenuEntry::Open,
    TrayMenuEntry::Pin,
    TrayMenuEntry::Settings,
    TrayMenuEntry::ResetOnboarding,
    TrayMenuEntry::Separator,
    TrayMenuEntry::Quit,
];
#[cfg(all(target_os = "linux", not(debug_assertions)))]
const MENU_LAYOUT: &[TrayMenuEntry] = &[
    TrayMenuEntry::Open,
    TrayMenuEntry::Pin,
    TrayMenuEntry::Settings,
    TrayMenuEntry::Separator,
    TrayMenuEntry::Quit,
];
#[cfg(all(not(target_os = "linux"), debug_assertions))]
const MENU_LAYOUT: &[TrayMenuEntry] = &[
    TrayMenuEntry::Pin,
    TrayMenuEntry::Settings,
    TrayMenuEntry::ResetOnboarding,
    TrayMenuEntry::Separator,
    TrayMenuEntry::Quit,
];
#[cfg(all(not(target_os = "linux"), not(debug_assertions)))]
const MENU_LAYOUT: &[TrayMenuEntry] = &[
    TrayMenuEntry::Pin,
    TrayMenuEntry::Settings,
    TrayMenuEntry::Separator,
    TrayMenuEntry::Quit,
];

/// The tray menu items whose text follows app state.
///
/// Held as managed state because the menu is built once and the pin item has to
/// be re-labelled later. Two things make that sound: `MenuItem<R>` is an
/// `Arc<MenuItemInner<R>>` that tauri declares `Send + Sync`, and `set_text`
/// marshals through `run_main_thread!`, which runs its closure inline when the
/// caller is already on the main thread — as [`on_menu_event`] is.
pub struct TrayMenu {
    pin: MenuItem<Wry>,
}

/// The label the pin item carries for a given state — it names the action, not
/// the condition, so a pinned window offers "Unpin Window".
fn pin_label(pinned: bool) -> &'static str {
    if pinned { UNPIN_LABEL } else { PIN_LABEL }
}

/// Builds the menu-bar item and wires up its click and menu handling.
pub fn create(app: &AppHandle) -> tauri::Result<TrayIcon> {
    let (menu, pin) = build_menu(app)?;
    app.manage(TrayMenu { pin });

    TrayIconBuilder::with_id(TRAY_ID)
        .icon(Image::from_bytes(TRAY_ICON)?)
        // macOS renders template images tinted for the current menu-bar
        // appearance, including the inverted pressed state.
        .icon_as_template(true)
        .tooltip("antiburn")
        .menu(&menu)
        // The menu belongs to the secondary button; the primary button is the
        // popover toggle. Linux ignores this option, because the AppIndicator
        // menu opens on every click.
        .show_menu_on_left_click(false)
        .on_tray_icon_event(on_tray_event)
        .on_menu_event(on_menu_event)
        .build(app)
}

/// Returns the menu and a handle to the one item that changes after the build.
///
/// The pin sits above Settings: it acts on the window the reader just had in
/// front of them, where the other two act on the application.
///
/// On Linux the menu is the only route into the popover, so Open goes first as
/// the default action. It needs no separator of its own, because it acts on the
/// same window the pin does.
fn build_menu(app: &AppHandle) -> tauri::Result<(Menu<Wry>, MenuItem<Wry>)> {
    let pin_item = MenuItem::with_id(
        app,
        MENU_PIN,
        pin_label(popover::is_pinned(app)),
        true,
        None::<&str>,
    )?;
    let settings_item = MenuItem::with_id(app, MENU_SETTINGS, "Settings…", true, None::<&str>)?;
    #[cfg(debug_assertions)]
    let reset_onboarding_item = MenuItem::with_id(
        app,
        MENU_RESET_ONBOARDING,
        RESET_ONBOARDING_LABEL,
        true,
        None::<&str>,
    )?;
    let separator = PredefinedMenuItem::separator(app)?;
    let quit_item = MenuItem::with_id(app, MENU_QUIT, "Quit antiburn", true, None::<&str>)?;
    #[cfg(target_os = "linux")]
    let open_item = MenuItem::with_id(app, MENU_OPEN, OPEN_LABEL, true, None::<&str>)?;

    let items: Vec<&dyn IsMenuItem<Wry>> = MENU_LAYOUT
        .iter()
        .map(|entry| -> &dyn IsMenuItem<Wry> {
            match entry {
                #[cfg(target_os = "linux")]
                TrayMenuEntry::Open => &open_item,
                TrayMenuEntry::Pin => &pin_item,
                TrayMenuEntry::Settings => &settings_item,
                #[cfg(debug_assertions)]
                TrayMenuEntry::ResetOnboarding => &reset_onboarding_item,
                TrayMenuEntry::Separator => &separator,
                TrayMenuEntry::Quit => &quit_item,
            }
        })
        .collect();
    let menu = Menu::with_items(app, &items)?;
    Ok((menu, pin_item))
}

fn on_tray_event(tray: &TrayIcon, event: TrayIconEvent) {
    // Act on release, not press: pressing and dragging away should not toggle.
    if let TrayIconEvent::Click {
        button: MouseButton::Left,
        button_state: MouseButtonState::Up,
        rect,
        ..
    } = event
    {
        popover::toggle(tray.app_handle(), rect);
    }
}

fn on_menu_event(app: &AppHandle, event: MenuEvent) {
    match event.id().as_ref() {
        // The AppIndicator backend reports no click events, so this item is the
        // popover's entry point on Linux.
        #[cfg(target_os = "linux")]
        MENU_OPEN => popover::open_from_tray_menu(app),
        MENU_PIN => {
            // The item names the action, so choosing it always means "do the
            // other thing"; the popover is re-shown by `set_pinned`, because
            // opening this menu is what dismissed it.
            popover::set_pinned(app, !popover::is_pinned(app));
            // Read the state back rather than trusting what was asked for, so
            // the label can never claim a pin that did not take.
            let pinned = popover::is_pinned(app);
            if let Some(menu) = app.try_state::<TrayMenu>()
                && let Err(error) = menu.pin.set_text(pin_label(pinned))
            {
                // The pin itself took effect; only the label is stale, and the
                // next state change relabels it.
                ::tracing::warn!(
                    event = "tray_pin_relabel_failed",
                    pinned,
                    error = %error
                );
            }
        }
        MENU_SETTINGS => {
            // No pane in particular: the tray's Settings item is a general
            // entry point, so it leaves the window wherever it was last.
            if let Err(error) = settings::open(app, None) {
                ::tracing::error!(event = "settings_window_open_failed", error = %error);
            }
        }
        #[cfg(debug_assertions)]
        MENU_RESET_ONBOARDING => {
            if let Err(error) = commands::restart_onboarding(app.clone()) {
                ::tracing::error!(event = "onboarding_restart_failed", trigger = "tray", error);
            }
        }
        MENU_QUIT => {
            // Exit code 0 distinguishes a deliberate quit from the window
            // closes the shell suppresses (see `on_window_event`).
            app.exit(0);
        }
        _ => {}
    }
}

/// Light the menu-bar item, or put it out.
///
/// macOS only draws a *momentary* highlight on a status item: it appears on
/// mouse-down and lets go on mouse-up. So the icon would go flat the instant
/// the popover appeared, and the popover would read as a window floating near
/// the menu bar rather than as this item's surface. Every native menu-bar
/// popover stays lit for as long as it is open; this is how antiburn does the
/// same.
///
/// The state has to stay paired with the popover's visibility, and the pairing
/// lives in [`crate::popover`]: lit in `note_shown`, cleared in `note_hidden`.
/// Every open and every close already runs through that pair, so no caller —
/// including the tray menu's own pin — has to remember the icon separately.
///
/// # A known flicker on the opening click
///
/// tray-icon's `mouseUp:` calls `highlight(false)` and only then hands the
/// click on, so this function re-lights a button that went dark ~185µs
/// earlier. That gap is visible: `NSCell`'s highlight drawing is immediate and
/// flushed, not deferred to the next frame, so the dark state reaches the
/// screen as its own paint. Opening the popover therefore blinks once.
///
/// Measured, not guessed — Tauri delivers the tray event ~13µs after
/// `mouseUp:` begins, so this is not event-loop latency and no reordering on
/// this side can close it. Two alternatives were tried and rejected against
/// the running app: driving the button's `state` instead (a status button is
/// momentary, so `state` has no rendering at all), and forcing
/// `PushOnPushOff` so `state` would paint a background (it still does not).
/// `highlight(_:)` is the only property that renders, and tray-icon clears it
/// on every mouse-up.
///
/// Removing the blink means stopping that call, which means carrying a fork of
/// tray-icon rather than tracking the upstream revision already pinned in
/// `Cargo.toml`. Judged not worth it for one frame, deliberately rather than by
/// omission; the `[patch.crates-io]` note records the same decision.
///
/// macOS-only; a no-op elsewhere. Stateless — the caller says what the icon
/// should look like, not what to change.
#[cfg(target_os = "macos")]
pub fn set_highlight(app: &AppHandle, on: bool) {
    use objc2::MainThreadMarker;

    let Some(tray) = app.tray_by_id(TRAY_ID) else {
        return;
    };
    // Tauri marshals the closure onto the main thread either way: inline when
    // the caller is already there (the tray click, the window-event handler,
    // the global click monitor), or via a blocking event-loop round-trip when
    // it isn't (the `hide_popover` command, which runs on the async runtime).
    // The closure takes no lock, so neither path can deadlock.
    let _ = tray.with_inner_tray_icon(move |inner| {
        let Some(mtm) = MainThreadMarker::new() else {
            return;
        };
        let Some(item) = inner.ns_status_item() else {
            return;
        };
        let Some(button) = item.button(mtm) else {
            return;
        };
        button.highlight(on);
    });
}

#[cfg(not(target_os = "macos"))]
pub fn set_highlight(_app: &AppHandle, _on: bool) {}

#[cfg(test)]
mod tests {
    use super::*;

    /// A pinned window offers the way out, not a restatement of where it is.
    /// This is the whole contract of the item, so it is worth a test that does
    /// not need a menu to run.
    #[test]
    fn the_pin_item_always_names_the_action_it_would_take() {
        assert_eq!(pin_label(false), "Pin Window");
        assert_eq!(pin_label(true), "Unpin Window");
    }

    #[cfg(debug_assertions)]
    #[test]
    fn the_debug_menu_includes_the_reset_action() {
        assert_eq!(RESET_ONBOARDING_LABEL, "Reset Onboarding");
        assert!(MENU_LAYOUT.contains(&TrayMenuEntry::ResetOnboarding));
    }

    #[cfg(not(debug_assertions))]
    #[test]
    fn the_release_menu_excludes_debug_actions() {
        #[cfg(target_os = "linux")]
        assert_eq!(
            MENU_LAYOUT,
            &[
                TrayMenuEntry::Open,
                TrayMenuEntry::Pin,
                TrayMenuEntry::Settings,
                TrayMenuEntry::Separator,
                TrayMenuEntry::Quit,
            ]
        );
        #[cfg(not(target_os = "linux"))]
        assert_eq!(
            MENU_LAYOUT,
            &[
                TrayMenuEntry::Pin,
                TrayMenuEntry::Settings,
                TrayMenuEntry::Separator,
                TrayMenuEntry::Quit,
            ]
        );
    }
}
