// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! The menu-bar / system-tray item.
//!
//! Left click toggles the popover; right click opens a short menu. The menu
//! carries Quit because an agent application has no Dock icon and no
//! application menu — without it there would be no way to exit antiburn. It
//! also carries the popover's pin, which needs a surface that survives the
//! popover being dismissed — and the menu bar is the only one there is.

use tauri::AppHandle;
use tauri::image::Image;
use tauri::menu::{Menu, MenuEvent, MenuItem, PredefinedMenuItem};
use tauri::tray::{MouseButton, MouseButtonState, TrayIcon, TrayIconBuilder, TrayIconEvent};
use tauri::{Manager, Wry};

use crate::{popover, settings};

/// The tray item's id, and how anything else gets a handle back to it.
pub const TRAY_ID: &str = "antiburn";

/// Generated by `apps/desktop/scripts/generate-icons.mjs`; see the icons
/// README for provenance. Embedded rather than read at runtime so a damaged
/// installation cannot leave the app running with no menu-bar presence.
const TRAY_ICON: &[u8] = include_bytes!("../icons/tray.png");

const MENU_PIN: &str = "pin";
const MENU_SETTINGS: &str = "settings";
const MENU_QUIT: &str = "quit";

/// Title case, matching "Quit antiburn" and the platform's own menus.
const PIN_LABEL: &str = "Pin Window";
const UNPIN_LABEL: &str = "Unpin Window";

/// The tray menu items whose text follows app state.
///
/// Held as managed state because the menu is built once and the pin item has to
/// be re-labelled later. Two things make that sound: `MenuItem<R>` is an
/// `Arc<MenuItemInner<R>>` that tauri declares `Send + Sync`, and `set_text`
/// marshals through `run_main_thread!`, which runs its closure inline when the
/// caller is already on the main thread — as [`on_menu_event`] is.
pub struct TrayMenu {
    pin: MenuItem<Wry>,
}

/// The label the pin item carries for a given state — it names the action, not
/// the condition, so a pinned window offers "Unpin Window".
fn pin_label(pinned: bool) -> &'static str {
    if pinned { UNPIN_LABEL } else { PIN_LABEL }
}

/// Builds the menu-bar item and wires up its click and menu handling.
pub fn create(app: &AppHandle) -> tauri::Result<TrayIcon> {
    let (menu, pin) = build_menu(app)?;
    app.manage(TrayMenu { pin });

    TrayIconBuilder::with_id(TRAY_ID)
        .icon(Image::from_bytes(TRAY_ICON)?)
        // macOS renders template images tinted for the current menu-bar
        // appearance, including the inverted pressed state.
        .icon_as_template(true)
        .tooltip("antiburn")
        .menu(&menu)
        // The menu belongs to the secondary button; the primary button is the
        // popover toggle.
        .show_menu_on_left_click(false)
        .on_tray_icon_event(on_tray_event)
        .on_menu_event(on_menu_event)
        .build(app)
}

/// Returns the menu and a handle to the one item that changes after the build.
///
/// The pin sits above Settings: it acts on the window the reader just had in
/// front of them, where the other two act on the application.
fn build_menu(app: &AppHandle) -> tauri::Result<(Menu<Wry>, MenuItem<Wry>)> {
    let pin_item = MenuItem::with_id(
        app,
        MENU_PIN,
        pin_label(popover::is_pinned(app)),
        true,
        None::<&str>,
    )?;
    let settings_item = MenuItem::with_id(app, MENU_SETTINGS, "Settings…", true, None::<&str>)?;
    let separator = PredefinedMenuItem::separator(app)?;
    let quit_item = MenuItem::with_id(app, MENU_QUIT, "Quit antiburn", true, None::<&str>)?;

    let menu = Menu::with_items(app, &[&pin_item, &settings_item, &separator, &quit_item])?;
    Ok((menu, pin_item))
}

fn on_tray_event(tray: &TrayIcon, event: TrayIconEvent) {
    // Act on release, not press: pressing and dragging away should not toggle.
    if let TrayIconEvent::Click {
        button: MouseButton::Left,
        button_state: MouseButtonState::Up,
        rect,
        ..
    } = event
    {
        popover::toggle(tray.app_handle(), rect);
    }
}

fn on_menu_event(app: &AppHandle, event: MenuEvent) {
    match event.id().as_ref() {
        MENU_PIN => {
            // The item names the action, so choosing it always means "do the
            // other thing"; the popover is re-shown by `set_pinned`, because
            // opening this menu is what dismissed it.
            popover::set_pinned(app, !popover::is_pinned(app));
            // Read the state back rather than trusting what was asked for, so
            // the label can never claim a pin that did not take.
            let pinned = popover::is_pinned(app);
            if let Some(menu) = app.try_state::<TrayMenu>()
                && let Err(error) = menu.pin.set_text(pin_label(pinned))
            {
                // The pin itself took effect; only the label is stale, and the
                // next state change relabels it.
                eprintln!("antiburn: could not relabel the pin item ({error})");
            }
        }
        MENU_SETTINGS => {
            // No pane in particular: the tray's Settings item is a general
            // entry point, so it leaves the window wherever it was last.
            if let Err(error) = settings::open(app, None) {
                eprintln!("antiburn: could not open settings ({error})");
            }
        }
        MENU_QUIT => {
            // Exit code 0 distinguishes a deliberate quit from the window
            // closes the shell suppresses (see `on_window_event`).
            app.exit(0);
        }
        _ => {}
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A pinned window offers the way out, not a restatement of where it is.
    /// This is the whole contract of the item, so it is worth a test that does
    /// not need a menu to run.
    #[test]
    fn the_pin_item_always_names_the_action_it_would_take() {
        assert_eq!(pin_label(false), "Pin Window");
        assert_eq!(pin_label(true), "Unpin Window");
    }
}
